# Generated by Django 4.2.2 on 2023-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Album',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='Artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='Year',
            field=models.CharField(max_length=200),
        ),
    ]
